name: Linux

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev -yq

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Native Image
        run: ./gradlew nativeBuild

      - name: JLink Build
        run: ./gradlew jlinkZip

      - name: Rename artifact
        run: mv modules/frontend/build/gluonfx/x86_64-linux/frontend modules/frontend/build/gluonfx/x86_64-linux/ENBManager

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            modules/frontend/build/gluonfx/x86_64-linux/ENBManager
            modules/frontend/build/image/enbmanager-linux*.zip
